# Generated by Django 6.0.1 on 2026-01-20 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.user'),
        ),
    ]
