# Generated by Django 6.0.1 on 2026-01-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='assigned_user',
        ),
    ]
