# Generated by Django 6.0.1 on 2026-01-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.user'),
        ),
    ]
