# Generated by Django 6.0.1 on 2026-01-21 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_vehicle_assigned_user_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_data', models.DateField()),
                ('service_type', models.CharField(choices=[('Oil Change', 'Oil Change'), ('Tire Replacement', 'Tire Replacement'), ('Engine Check', 'Engine Check'), ('Other', 'Other')], max_length=50)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_histories', to='vehicles.vehicle')),
                ('vehicle_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
