# Generated by Django 6.0.1 on 2026-01-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_servicehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicehistory',
            old_name='service_data',
            new_name='service_date',
        ),
    ]
