# Generated by Django 6.0.1 on 2026-01-21 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_rename_service_data_servicehistory_service_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicehistory',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='vehicle_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_histories', to='vehicles.vehicle'),
        ),
    ]
