# Generated by Django 6.0.1 on 2026-01-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_remove_servicehistory_vehicle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicehistory',
            old_name='username',
            new_name='user',
        ),
    ]
